#ifndef APP_LED_H
#define APP_LED_H

#define APP_LED_BLINK_INTERVAL_FAST_MS 50U
#define APP_LED_BLINK_INTERVAL_NORMAL_MS 150U
#define APP_LED_BLINK_INTERVAL_SLOW_MS 1000U

enum app_led_mode {
    APP_LED_MODE_RUN = 0,
    APP_LED_MODE_OTA_UPDATING,
    APP_LED_MODE_OTA_ERROR,
};

#endif
