#ifndef APP_GPIO_MAP_H
#define APP_GPIO_MAP_H

#include <stdbool.h>
#include <stdint.h>

#define APP_GPIO_UNUSED_PIN (-1)

enum app_gpio_pin {
	APP_GPIO_LED_PIN = 42,

	APP_GPIO_I2C_SDA_PIN = 9,
	APP_GPIO_I2C_SCL_PIN = 10,

	APP_GPIO_BNO085_SDA_PIN = APP_GPIO_I2C_SDA_PIN,
	APP_GPIO_BNO085_SCL_PIN = APP_GPIO_I2C_SCL_PIN,

	APP_GPIO_MAX77958_SDA_PIN = APP_GPIO_I2C_SDA_PIN,
	APP_GPIO_MAX77958_SCL_PIN = APP_GPIO_I2C_SCL_PIN,

	APP_GPIO_BQ25792_SDA_PIN = APP_GPIO_I2C_SDA_PIN,
	APP_GPIO_BQ25792_SCL_PIN = APP_GPIO_I2C_SCL_PIN,

	APP_GPIO_UWB_RST_PIN = 8,
	APP_GPIO_UWB_IRQ_PIN = 6,
	APP_GPIO_UWB_CS_PIN = 48,
	APP_GPIO_UWB_WAKEUP_PIN = 7,

	APP_GPIO_SPI_MOSI_PIN = 11,
	APP_GPIO_SPI_SCK_PIN = 12,
	APP_GPIO_SPI_MISO_PIN = 13,

	APP_GPIO_GPS_ENABLE_PIN = 47,
	APP_GPIO_GPS_RX_PIN = 18,
	APP_GPIO_GPS_TX_PIN = 17,

	APP_GPIO_RTCM_TX_PIN = 1,
};

enum app_gpio_baud {
	APP_GPIO_GPS_BAUD = 115200,
	APP_GPIO_RTCM_BAUD = 115200,
};

enum app_gpio_dw3000_led {
	APP_GPIO_UWB_TX_DW_LED_INDEX = 3,
	APP_GPIO_UWB_RX_DW_LED_INDEX = 2,
};

static const bool APP_GPIO_UWB_RST_ACTIVE_HIGH = true;
static const bool APP_GPIO_UWB_WAKEUP_ACTIVE_HIGH = true;

#endif
