#ifndef APP_CONFIG_H
#define APP_CONFIG_H

/*
 * Non-secret application defaults live here and are versioned with the
 * firmware. Credentials and tokens stay in secrets.h.
 */

#define APP_RUNTIME_MODE_UWB_BEACON_SMOKE 0
#define APP_RUNTIME_MODE_UWB_DISTANCE_TEST 1
#define APP_RUNTIME_MODE_UWB_ANTENNA_DELAY_CALIBRATION 2
#define APP_RUNTIME_MODE_UWB_RANGING 3
#define APP_RUNTIME_MODE_UWB_ANCHOR_SURVEY 4

#ifndef APP_RUNTIME_MODE
#define APP_RUNTIME_MODE APP_RUNTIME_MODE_UWB_RANGING
#endif

#ifndef APP_WIFI_SSID
#define APP_WIFI_SSID "ED313"
#endif

#ifndef APP_UWB_ENABLED
#define APP_UWB_ENABLED 1
#endif

#ifndef APP_IDENTITY_HOSTNAME_PREFIX
#define APP_IDENTITY_HOSTNAME_PREFIX "uwb-module-"
#endif

/*
 * 0 = read module ID from NVS. Set to 1 only for a provisioning boot that
 * should write APP_IDENTITY_PROVISION_MODULE_ID to NVS. Keep this at 0 in the
 * common firmware after the provisioning flash.
 */
#ifndef APP_IDENTITY_PROVISION_ENABLED
#define APP_IDENTITY_PROVISION_ENABLED 0
#endif

#ifndef APP_IDENTITY_PROVISION_MODULE_ID
#define APP_IDENTITY_PROVISION_MODULE_ID 0
#endif

#ifndef APP_IDENTITY_PROVISION_UWB_ROLE_ENABLED
#define APP_IDENTITY_PROVISION_UWB_ROLE_ENABLED 0
#endif

#ifndef APP_IDENTITY_PROVISION_UWB_ROLE
#define APP_IDENTITY_PROVISION_UWB_ROLE 0
#endif

/* Optional fallback if NVS is empty and no legacy HOSTNAME suffix is present. */
#ifndef APP_IDENTITY_DEFAULT_MODULE_ID
#define APP_IDENTITY_DEFAULT_MODULE_ID 0
#endif

#ifndef APP_WIFI_USE_WPA3
#define APP_WIFI_USE_WPA3 0
#endif

#ifndef APP_WIFI_ALLOW_WPA_COMPAT
#define APP_WIFI_ALLOW_WPA_COMPAT 1
#endif

#ifndef APP_WIFI_PMF_CAPABLE
#define APP_WIFI_PMF_CAPABLE 1
#endif

#ifndef APP_WIFI_DISABLE_WPA3_COMPATIBLE_MODE
#define APP_WIFI_DISABLE_WPA3_COMPATIBLE_MODE 0
#endif

#ifndef APP_WIFI_FORCE_HT20
#define APP_WIFI_FORCE_HT20 1
#endif

#ifndef APP_WIFI_ENABLE_11B
#define APP_WIFI_ENABLE_11B 1
#endif

#ifndef APP_WIFI_SET_PROTOCOL
#define APP_WIFI_SET_PROTOCOL 0
#endif

#ifndef APP_WIFI_SCAN_BEFORE_CONNECT
#define APP_WIFI_SCAN_BEFORE_CONNECT 1
#endif

#ifndef APP_WIFI_SCAN_ON_RECONNECT_EVERY
#define APP_WIFI_SCAN_ON_RECONNECT_EVERY 5
#endif

#ifndef APP_WIFI_SCAN_MAX_APS
#define APP_WIFI_SCAN_MAX_APS 16
#endif

#ifndef APP_WIFI_SCAN_CHANNEL
#define APP_WIFI_SCAN_CHANNEL 0
#endif

#ifndef APP_WIFI_SCAN_ACTIVE_MIN_MS
#define APP_WIFI_SCAN_ACTIVE_MIN_MS 100
#endif

#ifndef APP_WIFI_SCAN_ACTIVE_MAX_MS
#define APP_WIFI_SCAN_ACTIVE_MAX_MS 300
#endif

#ifndef APP_WIFI_LOCK_BSSID
#define APP_WIFI_LOCK_BSSID 0
#endif

#ifndef APP_WIFI_BSSID
#define APP_WIFI_BSSID ""
#endif

#ifndef APP_WIFI_LOCK_CHANNEL
#define APP_WIFI_LOCK_CHANNEL 0
#endif

#ifndef APP_WIFI_RECONNECT_FOREVER
#define APP_WIFI_RECONNECT_FOREVER 1
#endif

#ifndef APP_WIFI_MAX_RETRIES
#define APP_WIFI_MAX_RETRIES 10
#endif

#ifndef APP_WIFI_RECONNECT_BASE_DELAY_MS
#define APP_WIFI_RECONNECT_BASE_DELAY_MS 500
#endif

#ifndef APP_WIFI_RECONNECT_MAX_DELAY_MS
#define APP_WIFI_RECONNECT_MAX_DELAY_MS 5000
#endif

#ifndef APP_WIFI_CONNECT_TIMEOUT_MS
#define APP_WIFI_CONNECT_TIMEOUT_MS 30000
#endif

#ifndef APP_WIFI_FAILURE_RETRY_COUNT
#define APP_WIFI_FAILURE_RETRY_COUNT 3
#endif

#ifndef APP_WIRELESS_LOG_ENABLED
#define APP_WIRELESS_LOG_ENABLED 1
#endif

#ifndef APP_WIRELESS_LOG_TARGET
#define APP_WIRELESS_LOG_TARGET "192.168.139.87"
#endif

#ifndef APP_WIRELESS_LOG_PORT
#define APP_WIRELESS_LOG_PORT 6055
#endif

#ifndef APP_STABILITY_LOG_STRESS_ENABLED
#define APP_STABILITY_LOG_STRESS_ENABLED 0
#endif

#ifndef APP_STABILITY_LOG_STRESS_INTERVAL_MS
#define APP_STABILITY_LOG_STRESS_INTERVAL_MS 100
#endif

#ifndef APP_STABILITY_LOG_STRESS_BURST_LINES
#define APP_STABILITY_LOG_STRESS_BURST_LINES 10
#endif

#ifndef APP_STABILITY_LOG_STRESS_PAYLOAD_BYTES
#define APP_STABILITY_LOG_STRESS_PAYLOAD_BYTES 96
#endif

#ifndef APP_STABILITY_LOG_STRESS_SUMMARY_INTERVAL_MS
#define APP_STABILITY_LOG_STRESS_SUMMARY_INTERVAL_MS 5000
#endif

#ifndef APP_BNO085_ACCEL_TEST_ENABLED
#define APP_BNO085_ACCEL_TEST_ENABLED 0
#endif

#ifndef APP_BNO085_I2C_ADDRESS
#define APP_BNO085_I2C_ADDRESS 0x4A
#endif

#ifndef APP_BNO085_I2C_CLOCK_HZ
#define APP_BNO085_I2C_CLOCK_HZ 100000
#endif

#ifndef APP_BNO085_ACCEL_INTERVAL_MS
#define APP_BNO085_ACCEL_INTERVAL_MS 50
#endif

#ifndef APP_BNO085_LOG_INTERVAL_MS
#define APP_BNO085_LOG_INTERVAL_MS 1000
#endif

#ifndef APP_BNO085_INT_WAIT_TIMEOUT_MS
#define APP_BNO085_INT_WAIT_TIMEOUT_MS 250
#endif

#endif /* APP_CONFIG_H */
