#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#define BOARD_CONFIG_GPIO_UNUSED (-1)

enum {
    BOARD_CONFIG_STATUS_LED_GPIO = 42,
    BOARD_CONFIG_STATUS_LED_ACTIVE_LEVEL = 1,

    BOARD_CONFIG_I2C_SDA_GPIO = 9,
    BOARD_CONFIG_I2C_SCL_GPIO = 10,

    BOARD_CONFIG_BNO085_SDA_GPIO = BOARD_CONFIG_I2C_SDA_GPIO,
    BOARD_CONFIG_BNO085_SCL_GPIO = BOARD_CONFIG_I2C_SCL_GPIO,
    BOARD_CONFIG_BNO085_RST_GPIO = 40,
    BOARD_CONFIG_BNO085_INT_GPIO = 15,
    BOARD_CONFIG_BNO085_RST_ACTIVE_LEVEL = 0,
    BOARD_CONFIG_BNO085_INT_ACTIVE_LEVEL = 0,

    BOARD_CONFIG_MAX77958_SDA_GPIO = BOARD_CONFIG_I2C_SDA_GPIO,
    BOARD_CONFIG_MAX77958_SCL_GPIO = BOARD_CONFIG_I2C_SCL_GPIO,

    BOARD_CONFIG_BQ25792_SDA_GPIO = BOARD_CONFIG_I2C_SDA_GPIO,
    BOARD_CONFIG_BQ25792_SCL_GPIO = BOARD_CONFIG_I2C_SCL_GPIO,
    BOARD_CONFIG_BQ25792_INT_GPIO = 4,
    BOARD_CONFIG_BQ25792_INT_ACTIVE_LEVEL = 0,
    BOARD_CONFIG_BQ25792_QON_GPIO = 38,
    BOARD_CONFIG_BQ25792_QON_ACTIVE_LEVEL = 0,
    BOARD_CONFIG_BQ25792_PG_GPIO = 5,
    BOARD_CONFIG_BQ25792_PG_ACTIVE_LEVEL = 0,

    BOARD_CONFIG_UWB_RST_GPIO = 8,
    BOARD_CONFIG_UWB_IRQ_GPIO = 6,
    BOARD_CONFIG_UWB_CS_GPIO = 48,
    BOARD_CONFIG_UWB_WAKEUP_GPIO = 7,

    BOARD_CONFIG_SPI_MOSI_GPIO = 11,
    BOARD_CONFIG_SPI_SCK_GPIO = 12,
    BOARD_CONFIG_SPI_MISO_GPIO = 13,

    BOARD_CONFIG_GPS_ENABLE_GPIO = 47,
    BOARD_CONFIG_GPS_ENABLE_ACTIVE_LEVEL = 1,
    BOARD_CONFIG_GPS_RX_GPIO = 18,
    BOARD_CONFIG_GPS_TX_GPIO = 17,
    BOARD_CONFIG_GPS_BAUD = 115200,

    BOARD_CONFIG_RTCM_TX_GPIO = 1,
    BOARD_CONFIG_RTCM_BAUD = 115200,

    BOARD_CONFIG_UWB_RXOK_DW_LED_INDEX = 0,
    BOARD_CONFIG_UWB_SFD_DW_LED_INDEX = 1,
    BOARD_CONFIG_UWB_RX_DW_LED_INDEX = 2,
    BOARD_CONFIG_UWB_TX_DW_LED_INDEX = 3,
};

/* ESP GPIO8 drives the gate of Q3/BSS138. GPIO high pulls DWM3000 ~RST low,
 * so reset is active-high from the ESP side even though the DWM3000 pin is
 * active-low.
 */
#define BOARD_CONFIG_UWB_RST_ACTIVE_HIGH 1
#define BOARD_CONFIG_UWB_WAKEUP_ACTIVE_HIGH 1

#endif
