#ifndef UWB_CONFIG_H
#define UWB_CONFIG_H

/*
 * UWB module behavior, IDs, and ranging defaults live here. Board wiring
 * remains in board_config.h; the selected firmware runtime stays in
 * app_config.h.
 */

#define APP_UWB_ROLE_UNSET 0
#define APP_UWB_ROLE_ANCHOR 1
#define APP_UWB_ROLE_TAG 2
#define APP_UWB_ROLE_DISTANCE_TEST_NODE 3

#ifndef APP_UWB_ROLE
#define APP_UWB_ROLE APP_UWB_ROLE_UNSET
#endif

/* 0 = derive from persistent app identity module ID, then Wi-Fi MAC fallback. */
#ifndef APP_UWB_SOURCE_ID
#define APP_UWB_SOURCE_ID 0
#endif

#ifndef APP_UWB_TAG_ID
#define APP_UWB_TAG_ID 1
#endif

#ifndef APP_UWB_ANCHOR_COUNT
#define APP_UWB_ANCHOR_COUNT 4
#endif

#ifndef APP_UWB_ANCHOR_0_ID
#define APP_UWB_ANCHOR_0_ID 2
#endif

#ifndef APP_UWB_ANCHOR_1_ID
#define APP_UWB_ANCHOR_1_ID 3
#endif

#ifndef APP_UWB_ANCHOR_2_ID
#define APP_UWB_ANCHOR_2_ID 4
#endif

#ifndef APP_UWB_ANCHOR_3_ID
#define APP_UWB_ANCHOR_3_ID 5
#endif

/* Validated ESP32-S3 FlexTDOA CI-CR radio-slot timing. */
#ifndef APP_UWB_FLEX_TDOA_GUARD_US
#define APP_UWB_FLEX_TDOA_GUARD_US 500
#endif

#ifndef APP_UWB_FLEX_TDOA_REQUEST_SUBSLOT_US
#define APP_UWB_FLEX_TDOA_REQUEST_SUBSLOT_US 250
#endif

#ifndef APP_UWB_FLEX_TDOA_REQUEST_PROCESS_US
#define APP_UWB_FLEX_TDOA_REQUEST_PROCESS_US 1500
#endif

#ifndef APP_UWB_FLEX_TDOA_RESPONSE_SUBSLOT_US
#define APP_UWB_FLEX_TDOA_RESPONSE_SUBSLOT_US 250
#endif

#ifndef APP_UWB_FLEX_TDOA_RESPONSE_PROCESS_US
#define APP_UWB_FLEX_TDOA_RESPONSE_PROCESS_US 600
#endif

#ifndef APP_UWB_ANCHOR_SURVEY_COORDINATOR_ID
#define APP_UWB_ANCHOR_SURVEY_COORDINATOR_ID APP_UWB_TAG_ID
#endif

#ifndef APP_UWB_ANCHOR_SURVEY_RX_SLICE_MS
#define APP_UWB_ANCHOR_SURVEY_RX_SLICE_MS 100
#endif

#ifndef APP_UWB_ANCHOR_SURVEY_COMMAND_DELAY_MS
#define APP_UWB_ANCHOR_SURVEY_COMMAND_DELAY_MS 80
#endif

#ifndef APP_UWB_ANCHOR_SURVEY_SLOT_MS
#define APP_UWB_ANCHOR_SURVEY_SLOT_MS 1000
#endif

#ifndef APP_UWB_ANCHOR_SURVEY_ROUND_GAP_MS
#define APP_UWB_ANCHOR_SURVEY_ROUND_GAP_MS 1500
#endif

#ifndef APP_UWB_ANCHOR_SURVEY_PASSIVE_TAG_LOG_EVERY
#define APP_UWB_ANCHOR_SURVEY_PASSIVE_TAG_LOG_EVERY 20
#endif

#ifndef APP_UWB_RANGING_SLOT_MS
#define APP_UWB_RANGING_SLOT_MS 30
#endif

#ifndef APP_UWB_RANGING_ROUND_GAP_MS
#define APP_UWB_RANGING_ROUND_GAP_MS 4
#endif

#ifndef APP_UWB_RANGING_RX_SLICE_MS
#define APP_UWB_RANGING_RX_SLICE_MS 10
#endif

/* Native three-frame DS-TWR timing used only by UWB ranging mode. */
#ifndef APP_UWB_RANGING_RX_TIMEOUT_MS
#define APP_UWB_RANGING_RX_TIMEOUT_MS 12
#endif

#ifndef APP_UWB_RANGING_RESP_DELAY_MS
#define APP_UWB_RANGING_RESP_DELAY_MS 5
#endif

#ifndef APP_UWB_RANGING_FINAL_DELAY_MS
#define APP_UWB_RANGING_FINAL_DELAY_MS 5
#endif

#ifndef APP_UWB_RANGING_AUTO_RX_DELAY_UUS
#define APP_UWB_RANGING_AUTO_RX_DELAY_UUS 500
#endif

/* Native DS-TWR rejects physically impossible results before telemetry. */
#ifndef APP_UWB_RANGING_MAX_DISTANCE_M
#define APP_UWB_RANGING_MAX_DISTANCE_M 100.0
#endif

/*
 * Passive DS-TWR keeps the three POLL/RESP/FINAL packets but schedules
 * anchor-to-anchor exchanges. Any module outside the anchor set only listens
 * and derives TDOA observations without consuming radio airtime.
 */
#ifndef APP_UWB_PASSIVE_DS_SCHEDULE
#define APP_UWB_PASSIVE_DS_SCHEDULE 0
#endif

#ifndef APP_UWB_PASSIVE_DS_SLOT_MS
#define APP_UWB_PASSIVE_DS_SLOT_MS 5
#endif

#ifndef APP_UWB_PASSIVE_DS_ROUND_GAP_MS
#define APP_UWB_PASSIVE_DS_ROUND_GAP_MS 1
#endif

#ifndef APP_UWB_PASSIVE_DS_RX_SLICE_MS
#define APP_UWB_PASSIVE_DS_RX_SLICE_MS 100
#endif

#ifndef APP_UWB_PASSIVE_DS_RX_TIMEOUT_MS
#define APP_UWB_PASSIVE_DS_RX_TIMEOUT_MS 4
#endif

#ifndef APP_UWB_PASSIVE_DS_RESP_DELAY_US
#define APP_UWB_PASSIVE_DS_RESP_DELAY_US 1000
#endif

#ifndef APP_UWB_PASSIVE_DS_FINAL_DELAY_US
#define APP_UWB_PASSIVE_DS_FINAL_DELAY_US 1000
#endif

#ifndef APP_UWB_PASSIVE_DS_MULTI_RESPONSE_SPACING_US
#define APP_UWB_PASSIVE_DS_MULTI_RESPONSE_SPACING_US 750
#endif

/*
 * Validated FlexTDOA guard reused as a value, not as shared runtime state.
 * The dynamic multipoint profile places this guard after its exchange budget.
 */
#ifndef APP_UWB_PASSIVE_DS_DYNAMIC_GUARD_US
#define APP_UWB_PASSIVE_DS_DYNAMIC_GUARD_US 250
#endif

#ifndef APP_UWB_PASSIVE_DS_AUTO_RX_DELAY_UUS
#define APP_UWB_PASSIVE_DS_AUTO_RX_DELAY_UUS 500
#endif

/*
 * The established blocking exchange and one-solve-per-frame behavior remain
 * the firmware defaults. The deadline pipeline and rolling solver are
 * independent A/B controls selected at runtime.
 */
#ifndef APP_UWB_PASSIVE_DS_PIPELINE_MODE
#define APP_UWB_PASSIVE_DS_PIPELINE_MODE 0
#endif

#ifndef APP_UWB_PASSIVE_DS_SOLVE_MODE
#define APP_UWB_PASSIVE_DS_SOLVE_MODE 0
#endif

#ifndef APP_UWB_PASSIVE_DS_ROLLING_MAX_HZ
#define APP_UWB_PASSIVE_DS_ROLLING_MAX_HZ 100
#endif

#ifndef APP_UWB_ANTENNA_DELAY_DEFAULT
#define APP_UWB_ANTENNA_DELAY_DEFAULT 0x3FCA
#endif

#define APP_UWB_CALIBRATION_METHOD_TWO_MODULE 1
#define APP_UWB_CALIBRATION_METHOD_THREE_MODULE 2

#ifndef APP_UWB_CALIBRATION_METHOD
#define APP_UWB_CALIBRATION_METHOD APP_UWB_CALIBRATION_METHOD_TWO_MODULE
#endif

/* Known physical distance for the currently selected calibration setup. */
#ifndef APP_UWB_CALIBRATION_KNOWN_DISTANCE_MM
#define APP_UWB_CALIBRATION_KNOWN_DISTANCE_MM 2000
#endif

/*
 * Two-module calibration: reference initiates, DUT responds and logs the
 * statistics/suggested delay.
 */
#ifndef APP_UWB_CALIBRATION_REFERENCE_ID
#define APP_UWB_CALIBRATION_REFERENCE_ID 1
#endif

#ifndef APP_UWB_CALIBRATION_DUT_ID
#define APP_UWB_CALIBRATION_DUT_ID 2
#endif

/* Three-module EDM capture IDs. Each module will initiate to the other two. */
#ifndef APP_UWB_CALIBRATION_THREE_ID_0
#define APP_UWB_CALIBRATION_THREE_ID_0 1
#endif

#ifndef APP_UWB_CALIBRATION_THREE_ID_1
#define APP_UWB_CALIBRATION_THREE_ID_1 2
#endif

#ifndef APP_UWB_CALIBRATION_THREE_ID_2
#define APP_UWB_CALIBRATION_THREE_ID_2 3
#endif

#ifndef APP_UWB_CALIBRATION_THREE_DISTANCE_0_1_MM
#define APP_UWB_CALIBRATION_THREE_DISTANCE_0_1_MM APP_UWB_CALIBRATION_KNOWN_DISTANCE_MM
#endif

#ifndef APP_UWB_CALIBRATION_THREE_DISTANCE_0_2_MM
#define APP_UWB_CALIBRATION_THREE_DISTANCE_0_2_MM APP_UWB_CALIBRATION_KNOWN_DISTANCE_MM
#endif

#ifndef APP_UWB_CALIBRATION_THREE_DISTANCE_1_2_MM
#define APP_UWB_CALIBRATION_THREE_DISTANCE_1_2_MM APP_UWB_CALIBRATION_KNOWN_DISTANCE_MM
#endif

#ifndef APP_UWB_CALIBRATION_SAMPLE_COUNT
#define APP_UWB_CALIBRATION_SAMPLE_COUNT 200
#endif

#ifndef APP_UWB_CALIBRATION_SUMMARY_EVERY
#define APP_UWB_CALIBRATION_SUMMARY_EVERY 25
#endif

#ifndef APP_UWB_CALIBRATION_MIN_INTERVAL_MS
#define APP_UWB_CALIBRATION_MIN_INTERVAL_MS 100
#endif

#ifndef APP_UWB_CALIBRATION_MAX_INTERVAL_MS
#define APP_UWB_CALIBRATION_MAX_INTERVAL_MS 10
#endif

#ifndef APP_UWB_CALIBRATION_RX_SLICE_MS
#define APP_UWB_CALIBRATION_RX_SLICE_MS 50
#endif

#ifndef APP_UWB_CALIBRATION_COMMAND_DELAY_MS
#define APP_UWB_CALIBRATION_COMMAND_DELAY_MS 20
#endif

#ifndef APP_UWB_CALIBRATION_SLOT_GUARD_US
#define APP_UWB_CALIBRATION_SLOT_GUARD_US 500
#endif

#ifndef APP_UWB_CALIBRATION_SYNC_PREPARE_MS
#define APP_UWB_CALIBRATION_SYNC_PREPARE_MS 20
#endif

#ifndef APP_UWB_DW_LEDS_ENABLED
#define APP_UWB_DW_LEDS_ENABLED 1
#endif

#ifndef APP_UWB_DW_RXOK_LED_ENABLED
#define APP_UWB_DW_RXOK_LED_ENABLED 1
#endif

#ifndef APP_UWB_DW_SFD_LED_ENABLED
#define APP_UWB_DW_SFD_LED_ENABLED 1
#endif

#ifndef APP_UWB_DW_RX_LED_ENABLED
#define APP_UWB_DW_RX_LED_ENABLED 1
#endif

#ifndef APP_UWB_DW_TX_LED_ENABLED
#define APP_UWB_DW_TX_LED_ENABLED 1
#endif

#ifndef APP_UWB_DW_LEDS_INIT_BLINK
#define APP_UWB_DW_LEDS_INIT_BLINK 1
#endif

/* DW3000 LED blink time register value. 0x10 is the decadriver default. */
#ifndef APP_UWB_DW_LEDS_BLINK_TIME
#define APP_UWB_DW_LEDS_BLINK_TIME 0x10
#endif

#ifndef APP_UWB_BEACON_ENABLED
#define APP_UWB_BEACON_ENABLED 1
#endif

#ifndef APP_UWB_BEACON_MIN_INTERVAL_MS
#define APP_UWB_BEACON_MIN_INTERVAL_MS 700
#endif

#ifndef APP_UWB_BEACON_MAX_INTERVAL_MS
#define APP_UWB_BEACON_MAX_INTERVAL_MS 1900
#endif

#ifndef APP_UWB_DISTANCE_TEST_PEER_ID
#define APP_UWB_DISTANCE_TEST_PEER_ID 0
#endif

#ifndef APP_UWB_DISTANCE_TEST_INITIATOR_ID
#define APP_UWB_DISTANCE_TEST_INITIATOR_ID 1
#endif

#ifndef APP_UWB_DISTANCE_TEST_RESPONDER_ID
#define APP_UWB_DISTANCE_TEST_RESPONDER_ID 2
#endif

#ifndef APP_UWB_DISTANCE_TEST_INTERVAL_MS
#define APP_UWB_DISTANCE_TEST_INTERVAL_MS 1000
#endif

#ifndef APP_UWB_DISTANCE_TEST_RX_TIMEOUT_MS
#define APP_UWB_DISTANCE_TEST_RX_TIMEOUT_MS 100
#endif

#ifndef APP_UWB_DISTANCE_TEST_USE_DELAYED_TX
#define APP_UWB_DISTANCE_TEST_USE_DELAYED_TX 1
#endif

#ifndef APP_UWB_DISTANCE_TEST_AUTO_RX_AFTER_TX
#define APP_UWB_DISTANCE_TEST_AUTO_RX_AFTER_TX 1
#endif

#ifndef APP_UWB_DISTANCE_TEST_AUTO_RX_DELAY_UUS
#define APP_UWB_DISTANCE_TEST_AUTO_RX_DELAY_UUS 500
#endif

#ifndef APP_UWB_DISTANCE_TEST_RESP_DELAY_MS
#define APP_UWB_DISTANCE_TEST_RESP_DELAY_MS 20
#endif

#ifndef APP_UWB_DISTANCE_TEST_FINAL_DELAY_MS
#define APP_UWB_DISTANCE_TEST_FINAL_DELAY_MS 20
#endif

#ifndef APP_UWB_DISTANCE_TEST_REPORT_DELAY_MS
#define APP_UWB_DISTANCE_TEST_REPORT_DELAY_MS 10
#endif

#ifndef APP_UWB_DISTANCE_TEST_CLOCK_OFFSET_CORRECTION
#define APP_UWB_DISTANCE_TEST_CLOCK_OFFSET_CORRECTION 1
#endif

#ifndef APP_UWB_IRQ_ENABLED
#define APP_UWB_IRQ_ENABLED 1
#endif

#define APP_UWB_STS_MODE_OFF 0
#define APP_UWB_STS_MODE_1 1
#define APP_UWB_STS_MODE_2 2
#define APP_UWB_STS_MODE_ND 3
#define APP_UWB_STS_MODE_SDC 8

#ifndef APP_UWB_STS_MODE
#define APP_UWB_STS_MODE APP_UWB_STS_MODE_OFF
#endif

#ifndef APP_UWB_STS_LENGTH_SYMBOLS
#define APP_UWB_STS_LENGTH_SYMBOLS 64
#endif

#define APP_UWB_RADIO_PROFILE_LEGACY_CH5_6M8_PLEN128 1
#define APP_UWB_RADIO_PROFILE_LEGACY_CH9_6M8_PLEN128 2
#define APP_UWB_RADIO_BR_850K 0
#define APP_UWB_RADIO_BR_6M8 1
#define APP_UWB_RADIO_PLEN_32 0x04
#define APP_UWB_RADIO_PLEN_64 0x01
#define APP_UWB_RADIO_PLEN_72 0x07
#define APP_UWB_RADIO_PLEN_128 0x05
#define APP_UWB_RADIO_PLEN_256 0x09
#define APP_UWB_RADIO_PLEN_512 0x0D
#define APP_UWB_RADIO_PLEN_1024 0x02
#define APP_UWB_RADIO_PLEN_1536 0x06
#define APP_UWB_RADIO_PLEN_2048 0x0A

#ifndef APP_UWB_RADIO_PROFILE
#define APP_UWB_RADIO_PROFILE APP_UWB_RADIO_PROFILE_LEGACY_CH5_6M8_PLEN128
#endif

#ifndef APP_UWB_RADIO_CHANNEL
#if APP_UWB_RADIO_PROFILE == APP_UWB_RADIO_PROFILE_LEGACY_CH9_6M8_PLEN128
#define APP_UWB_RADIO_CHANNEL 9
#else
#define APP_UWB_RADIO_CHANNEL 5
#endif
#endif

#ifndef APP_UWB_RADIO_RF_CHANNEL_BIT
#if APP_UWB_RADIO_PROFILE == APP_UWB_RADIO_PROFILE_LEGACY_CH9_6M8_PLEN128
#define APP_UWB_RADIO_RF_CHANNEL_BIT 1
#else
#define APP_UWB_RADIO_RF_CHANNEL_BIT 0
#endif
#endif

#ifndef APP_UWB_RADIO_PREAMBLE_LEN_CODE
#define APP_UWB_RADIO_PREAMBLE_LEN_CODE APP_UWB_RADIO_PLEN_128
#endif

#ifndef APP_UWB_RADIO_PREAMBLE_CODE
#define APP_UWB_RADIO_PREAMBLE_CODE 10
#endif

#ifndef APP_UWB_RADIO_PAC
#define APP_UWB_RADIO_PAC 0
#endif

#ifndef APP_UWB_RADIO_DATA_RATE
#define APP_UWB_RADIO_DATA_RATE APP_UWB_RADIO_BR_6M8
#endif

#ifndef APP_UWB_RADIO_PHR_MODE
#define APP_UWB_RADIO_PHR_MODE 0
#endif

#ifndef APP_UWB_RADIO_PHR_RATE
#define APP_UWB_RADIO_PHR_RATE 1
#endif

#ifndef APP_UWB_RADIO_SFD_TYPE
#define APP_UWB_RADIO_SFD_TYPE 1
#endif

#ifndef APP_UWB_RADIO_TX_PG_DELAY
#define APP_UWB_RADIO_TX_PG_DELAY 0x34
#endif

#ifndef APP_UWB_RADIO_TX_POWER
#define APP_UWB_RADIO_TX_POWER 0xFDFDFDFD
#endif

#define APP_UWB_RADIO_RF_TX_CTRL_2_CH9 0x1C010034
#define APP_UWB_RADIO_RF_TX_CTRL_2_CH5 0x1C071134

#ifndef APP_UWB_RADIO_RF_TX_CTRL_2
#if APP_UWB_RADIO_PROFILE == APP_UWB_RADIO_PROFILE_LEGACY_CH9_6M8_PLEN128
#define APP_UWB_RADIO_RF_TX_CTRL_2 APP_UWB_RADIO_RF_TX_CTRL_2_CH9
#else
#define APP_UWB_RADIO_RF_TX_CTRL_2 APP_UWB_RADIO_RF_TX_CTRL_2_CH5
#endif
#endif

#ifndef APP_UWB_RADIO_PLL_CFG
#define APP_UWB_RADIO_PLL_CFG 0x0F3C
#endif

#ifndef APP_UWB_RADIO_RF_0X51
#define APP_UWB_RADIO_RF_0X51 0x14
#endif

#ifndef APP_UWB_RADIO_RF_TX_CTRL_1
#define APP_UWB_RADIO_RF_TX_CTRL_1 0x0E
#endif

#ifndef APP_UWB_RADIO_PLL_CAL
#define APP_UWB_RADIO_PLL_CAL 0x81
#endif

#define APP_UWB_RADIO_PLL_CFG_FINAL_CH9 0x0F3C
#define APP_UWB_RADIO_PLL_CFG_FINAL_CH5 0x1F3C

#ifndef APP_UWB_RADIO_PLL_CFG_FINAL
#if APP_UWB_RADIO_PROFILE == APP_UWB_RADIO_PROFILE_LEGACY_CH9_6M8_PLEN128
#define APP_UWB_RADIO_PLL_CFG_FINAL APP_UWB_RADIO_PLL_CFG_FINAL_CH9
#else
#define APP_UWB_RADIO_PLL_CFG_FINAL APP_UWB_RADIO_PLL_CFG_FINAL_CH5
#endif
#endif

#ifndef APP_UWB_RADIO_PLL_CAL_FINAL
#define APP_UWB_RADIO_PLL_CAL_FINAL 0x81
#endif

#define APP_UWB_DGC_LUT_CH9_0 0x0002A8FE
#define APP_UWB_DGC_LUT_CH9_1 0x0002AC36
#define APP_UWB_DGC_LUT_CH9_2 0x0002A5FE
#define APP_UWB_DGC_LUT_CH9_3 0x0002AF3E
#define APP_UWB_DGC_LUT_CH9_4 0x0002AF7D
#define APP_UWB_DGC_LUT_CH9_5 0x0002AFB5
#define APP_UWB_DGC_LUT_CH9_6 0x0002AFB5

#define APP_UWB_DGC_LUT_CH5_0 0x0001C0FD
#define APP_UWB_DGC_LUT_CH5_1 0x0001C43E
#define APP_UWB_DGC_LUT_CH5_2 0x0001C6BE
#define APP_UWB_DGC_LUT_CH5_3 0x0001C77E
#define APP_UWB_DGC_LUT_CH5_4 0x0001CF36
#define APP_UWB_DGC_LUT_CH5_5 0x0001CFB5
#define APP_UWB_DGC_LUT_CH5_6 0x0001CFF5

#ifndef APP_UWB_DGC_LUT_0
#if APP_UWB_RADIO_PROFILE == APP_UWB_RADIO_PROFILE_LEGACY_CH9_6M8_PLEN128
#define APP_UWB_DGC_LUT_0 APP_UWB_DGC_LUT_CH9_0
#define APP_UWB_DGC_LUT_1 APP_UWB_DGC_LUT_CH9_1
#define APP_UWB_DGC_LUT_2 APP_UWB_DGC_LUT_CH9_2
#define APP_UWB_DGC_LUT_3 APP_UWB_DGC_LUT_CH9_3
#define APP_UWB_DGC_LUT_4 APP_UWB_DGC_LUT_CH9_4
#define APP_UWB_DGC_LUT_5 APP_UWB_DGC_LUT_CH9_5
#define APP_UWB_DGC_LUT_6 APP_UWB_DGC_LUT_CH9_6
#else
#define APP_UWB_DGC_LUT_0 APP_UWB_DGC_LUT_CH5_0
#define APP_UWB_DGC_LUT_1 APP_UWB_DGC_LUT_CH5_1
#define APP_UWB_DGC_LUT_2 APP_UWB_DGC_LUT_CH5_2
#define APP_UWB_DGC_LUT_3 APP_UWB_DGC_LUT_CH5_3
#define APP_UWB_DGC_LUT_4 APP_UWB_DGC_LUT_CH5_4
#define APP_UWB_DGC_LUT_5 APP_UWB_DGC_LUT_CH5_5
#define APP_UWB_DGC_LUT_6 APP_UWB_DGC_LUT_CH5_6
#endif
#endif

#ifndef APP_UWB_DIAGNOSTICS_ENABLED
#define APP_UWB_DIAGNOSTICS_ENABLED 1
#endif

#ifndef APP_UWB_DIAGNOSTICS_LOG_EVERY
#define APP_UWB_DIAGNOSTICS_LOG_EVERY 5
#endif

#ifndef APP_UWB_EVENT_COUNTERS_ENABLED
#define APP_UWB_EVENT_COUNTERS_ENABLED 1
#endif

#ifndef APP_UWB_EVENT_COUNTERS_LOG_EVERY
#define APP_UWB_EVENT_COUNTERS_LOG_EVERY 10
#endif

#endif /* UWB_CONFIG_H */
