#ifndef UWB_CONFIG_H
#define UWB_CONFIG_H

/*
 * UWB module behavior, IDs, and ranging defaults live here. Board wiring
 * remains in board_config.h; the selected firmware runtime stays in
 * app_config.h.
 */

#define APP_UWB_ROLE_UNSET 0
#define APP_UWB_ROLE_ANCHOR 1
#define APP_UWB_ROLE_TAG 2
#define APP_UWB_ROLE_DISTANCE_TEST_NODE 3

#ifndef APP_UWB_ROLE
#define APP_UWB_ROLE APP_UWB_ROLE_UNSET
#endif

/* 0 = derive from persistent app identity module ID, then Wi-Fi MAC fallback. */
#ifndef APP_UWB_SOURCE_ID
#define APP_UWB_SOURCE_ID 0
#endif

#ifndef APP_UWB_TAG_ID
#define APP_UWB_TAG_ID 100
#endif

#ifndef APP_UWB_ANCHOR_COUNT
#define APP_UWB_ANCHOR_COUNT 4
#endif

#ifndef APP_UWB_ANCHOR_0_ID
#define APP_UWB_ANCHOR_0_ID 1
#endif

#ifndef APP_UWB_ANCHOR_1_ID
#define APP_UWB_ANCHOR_1_ID 2
#endif

#ifndef APP_UWB_ANCHOR_2_ID
#define APP_UWB_ANCHOR_2_ID 3
#endif

#ifndef APP_UWB_ANCHOR_3_ID
#define APP_UWB_ANCHOR_3_ID 4
#endif

#ifndef APP_UWB_ANTENNA_DELAY_DEFAULT
#define APP_UWB_ANTENNA_DELAY_DEFAULT 0x3FCA
#endif

#define APP_UWB_CALIBRATION_METHOD_TWO_MODULE 1
#define APP_UWB_CALIBRATION_METHOD_THREE_MODULE 2

#ifndef APP_UWB_CALIBRATION_METHOD
#define APP_UWB_CALIBRATION_METHOD APP_UWB_CALIBRATION_METHOD_TWO_MODULE
#endif

/* Known physical distance for the currently selected calibration setup. */
#ifndef APP_UWB_CALIBRATION_KNOWN_DISTANCE_MM
#define APP_UWB_CALIBRATION_KNOWN_DISTANCE_MM 2000
#endif

/*
 * Two-module calibration: reference initiates, DUT responds and logs the
 * statistics/suggested delay.
 */
#ifndef APP_UWB_CALIBRATION_REFERENCE_ID
#define APP_UWB_CALIBRATION_REFERENCE_ID 1
#endif

#ifndef APP_UWB_CALIBRATION_DUT_ID
#define APP_UWB_CALIBRATION_DUT_ID 2
#endif

/* Three-module EDM capture IDs. Each module will initiate to the other two. */
#ifndef APP_UWB_CALIBRATION_THREE_ID_0
#define APP_UWB_CALIBRATION_THREE_ID_0 1
#endif

#ifndef APP_UWB_CALIBRATION_THREE_ID_1
#define APP_UWB_CALIBRATION_THREE_ID_1 2
#endif

#ifndef APP_UWB_CALIBRATION_THREE_ID_2
#define APP_UWB_CALIBRATION_THREE_ID_2 3
#endif

#ifndef APP_UWB_CALIBRATION_THREE_DISTANCE_0_1_MM
#define APP_UWB_CALIBRATION_THREE_DISTANCE_0_1_MM APP_UWB_CALIBRATION_KNOWN_DISTANCE_MM
#endif

#ifndef APP_UWB_CALIBRATION_THREE_DISTANCE_0_2_MM
#define APP_UWB_CALIBRATION_THREE_DISTANCE_0_2_MM APP_UWB_CALIBRATION_KNOWN_DISTANCE_MM
#endif

#ifndef APP_UWB_CALIBRATION_THREE_DISTANCE_1_2_MM
#define APP_UWB_CALIBRATION_THREE_DISTANCE_1_2_MM APP_UWB_CALIBRATION_KNOWN_DISTANCE_MM
#endif

#ifndef APP_UWB_CALIBRATION_SAMPLE_COUNT
#define APP_UWB_CALIBRATION_SAMPLE_COUNT 200
#endif

#ifndef APP_UWB_CALIBRATION_SUMMARY_EVERY
#define APP_UWB_CALIBRATION_SUMMARY_EVERY 25
#endif

#ifndef APP_UWB_CALIBRATION_MIN_INTERVAL_MS
#define APP_UWB_CALIBRATION_MIN_INTERVAL_MS 800
#endif

#ifndef APP_UWB_CALIBRATION_MAX_INTERVAL_MS
#define APP_UWB_CALIBRATION_MAX_INTERVAL_MS 1600
#endif

#ifndef APP_UWB_CALIBRATION_RX_SLICE_MS
#define APP_UWB_CALIBRATION_RX_SLICE_MS 50
#endif

#ifndef APP_UWB_DW_LEDS_ENABLED
#define APP_UWB_DW_LEDS_ENABLED 1
#endif

#ifndef APP_UWB_DW_RXOK_LED_ENABLED
#define APP_UWB_DW_RXOK_LED_ENABLED 1
#endif

#ifndef APP_UWB_DW_SFD_LED_ENABLED
#define APP_UWB_DW_SFD_LED_ENABLED 1
#endif

#ifndef APP_UWB_DW_RX_LED_ENABLED
#define APP_UWB_DW_RX_LED_ENABLED 1
#endif

#ifndef APP_UWB_DW_TX_LED_ENABLED
#define APP_UWB_DW_TX_LED_ENABLED 1
#endif

#ifndef APP_UWB_DW_LEDS_INIT_BLINK
#define APP_UWB_DW_LEDS_INIT_BLINK 1
#endif

/* DW3000 LED blink time register value. 0x10 is the decadriver default. */
#ifndef APP_UWB_DW_LEDS_BLINK_TIME
#define APP_UWB_DW_LEDS_BLINK_TIME 0x10
#endif

#ifndef APP_UWB_BEACON_ENABLED
#define APP_UWB_BEACON_ENABLED 1
#endif

#ifndef APP_UWB_BEACON_MIN_INTERVAL_MS
#define APP_UWB_BEACON_MIN_INTERVAL_MS 700
#endif

#ifndef APP_UWB_BEACON_MAX_INTERVAL_MS
#define APP_UWB_BEACON_MAX_INTERVAL_MS 1900
#endif

#ifndef APP_UWB_DISTANCE_TEST_PEER_ID
#define APP_UWB_DISTANCE_TEST_PEER_ID 0
#endif

#ifndef APP_UWB_DISTANCE_TEST_INITIATOR_ID
#define APP_UWB_DISTANCE_TEST_INITIATOR_ID 1
#endif

#ifndef APP_UWB_DISTANCE_TEST_RESPONDER_ID
#define APP_UWB_DISTANCE_TEST_RESPONDER_ID 2
#endif

#ifndef APP_UWB_DISTANCE_TEST_INTERVAL_MS
#define APP_UWB_DISTANCE_TEST_INTERVAL_MS 1000
#endif

#ifndef APP_UWB_DISTANCE_TEST_RX_TIMEOUT_MS
#define APP_UWB_DISTANCE_TEST_RX_TIMEOUT_MS 250
#endif

#ifndef APP_UWB_DISTANCE_TEST_USE_DELAYED_TX
#define APP_UWB_DISTANCE_TEST_USE_DELAYED_TX 1
#endif

#ifndef APP_UWB_DISTANCE_TEST_RESP_DELAY_MS
#define APP_UWB_DISTANCE_TEST_RESP_DELAY_MS 20
#endif

#ifndef APP_UWB_DISTANCE_TEST_FINAL_DELAY_MS
#define APP_UWB_DISTANCE_TEST_FINAL_DELAY_MS 20
#endif

#ifndef APP_UWB_DISTANCE_TEST_REPORT_DELAY_MS
#define APP_UWB_DISTANCE_TEST_REPORT_DELAY_MS 10
#endif

#endif /* UWB_CONFIG_H */
